services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_TCP_PORT}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init/db:/docker-entrypoint-initdb.d
  bla:
    build: .
    depends_on:
      - db
    environment:
      PORT: ${SERVER_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ADDRESS: ${MYSQL_ADDRESS}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

volumes:
  mysql_data:
