services:
  db:
    container_name: bla-db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_TCP_PORT: ${DB_PORT}
    volumes:
      - bla_data:/var/lib/mysql
      - ./init/db:/docker-entrypoint-initdb.d
  server:
    container_name: bla-server
    build: .
    depends_on:
      - db
    environment:
      DOMAIN: ${DOMAIN}
      SERVER_PORT: ${SERVER_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_HOST: db
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

volumes:
  bla_data:
    external: true
